<?php

namespace RegistroVisitasOfertaBundle\Repository;

/**
 * RegistroVisitasOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroVisitasOfertaRepository extends \Doctrine\ORM\EntityRepository
{
}
