<?php

namespace PalabrasClaveDemandaBundle\Repository;

/**
 * PalabrasClaveDemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalabrasClaveDemandaRepository extends \Doctrine\ORM\EntityRepository
{
}
