<?php

namespace RegistroOfertasDemandasBundle\Repository;

/**
 * RegistroOfertasDemandasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroOfertasDemandasRepository extends \Doctrine\ORM\EntityRepository
{
}
