imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OfertaBundle/Resources/config/services.yml" }
    - { resource: "@ComentarioBundle/Resources/config/services.yml" }
    - { resource: "@AreaBundle/Resources/config/services.yml" }
    - { resource: "@DisciplinaBundle/Resources/config/services.yml" }
    - { resource: "@RamaBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@VisitasDiaBundle/Resources/config/services.yml" }
    - { resource: "@VisitasMesBundle/Resources/config/services.yml" }
    - { resource: "@VisitasAnioBundle/Resources/config/services.yml" }
    - { resource: "@RegistroOfertasDemandasBundle/Resources/config/services.yml" }
    - { resource: "@RegistroVisitasUsuarioBundle/Resources/config/services.yml" }
    - { resource: "@RegistroVisitasOfertaBundle/Resources/config/services.yml" }
    - { resource: "@TipoBundle/Resources/config/services.yml" }
    - { resource: "@PalabrasClaveOfertaBundle/Resources/config/services.yml" }
    - { resource: "@DemandaBundle/Resources/config/services.yml" }
    - { resource: "@RegistroVisitasDemandaBundle/Resources/config/services.yml" }
    - { resource: "@PalabrasClaveDemandaBundle/Resources/config/services.yml" }
    - { resource: "@PruebaBundle/Resources/config/services.yml" }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#brochures_directory: '%kernel.root_dir%/../web/uploads/brochures'

parameters:
    locale: en
    brochures_directory: '%kernel.root_dir%/../web/uploads/brochures/'
    debug_toolbar: false
    debug_redirects: false

framework:
    #esi:             ~
    secret:          "%secret%"
    translator: { fallbacks: es }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        memory:   %database_memory%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true



# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    username:  '%mailer_user%'
    password:  '%mailer_password%'

knp_paginator:
    page_range: 5                      # rango por defecto de paginas en los controles del paginador
    default_options:
        page_name: page                # nombre del parámetro de la URL para la página
        sort_field_name: sort          # nombre del parámetro de la URL para la ordenación
        sort_direction_name: direction # nombre del parámetro de la URL para la dirección(ASC o DESC)
        distinct: true                 # Garantizar resultados distintos
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig  # plantilla controles
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # plantilla links ordenación

twig:
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

knp_paginator:
    page_range: 5                      # rango por defecto de paginas en los controles del paginador
    default_options:
        page_name: page                # nombre del parámetro de la URL para la página
        sort_field_name: sort          # nombre del parámetro de la URL para la ordenación
        sort_direction_name: direction # nombre del parámetro de la URL para la dirección(ASC o DESC)
        distinct: true                 # Garantizar resultados distintos
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig' # sort link template

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: lorenrr1@gmail.com
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            from_email:
                address:        lorenrr1@gmail.com
                sender_name:    Demo Registration
    resetting:
        email:
            from_email:
                address:        lorenrr1@gmail.com
                sender_name:    Demo Resetting
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   email/password_resetting.email.twig
    registration:
        confirmation:
            template:   UserBundle:Registration:email.txt.twig

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~


remg_generator:
    entity:
        # available configuration formats are: 'annotation', 'yaml', 'xml' and 'php'.
        configuration_format: annotation
