<?php

namespace RegistroVisitasDemandaBundle\Repository;

/**
 * RegistroVisitasDemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroVisitasDemandaRepository extends \Doctrine\ORM\EntityRepository
{
}
