<?php

namespace RegistroVisitasUsuarioBundle\Repository;

/**
 * RegistroVisitasUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroVisitasUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
