<?php

namespace PalabrasClaveOfertaBundle\Repository;

/**
 * PalabrasClaveOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalabrasClaveOfertaRepository extends \Doctrine\ORM\EntityRepository
{
}
