addDisciplina:
    path:     /disciplinas/addDisciplina/
    defaults: { _controller: DisciplinaBundle:Default:addDisciplina }

editDisciplina:
    path:     /disciplinas/editarDisciplina/
    defaults: { _controller: DisciplinaBundle:Default:editarDisciplina }

select_disciplina:
    path:     /selectDisciplina/
    defaults: { _controller: DisciplinaBundle:Default:selectDisciplina }

deleteDisciplina:
    path:     /areas/deleteDisciplina/
    defaults: { _controller:DisciplinaBundle:Default:deleteDisciplina }