<?php

namespace Proxies\__CG__\OfertaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Oferta extends \OfertaBundle\Entity\Oferta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'id', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'nombre', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'autor', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'descripcion', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'condiciones', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaInicio', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaFin', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'contacto', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'brochure', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'comentarios', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'area', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'rama', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'disciplina', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'tipo'];
        }

        return ['__isInitialized__', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'id', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'nombre', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'autor', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'descripcion', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'condiciones', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaInicio', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaFin', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'contacto', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'brochure', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'comentarios', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'area', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'rama', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'disciplina', '' . "\0" . 'OfertaBundle\\Entity\\Oferta' . "\0" . 'tipo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Oferta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutor($autor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutor', [$autor]);

        return parent::setAutor($autor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutor', []);

        return parent::getAutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondiciones($condiciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondiciones', [$condiciones]);

        return parent::setCondiciones($condiciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondiciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondiciones', []);

        return parent::getCondiciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', [$fechaInicio]);

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', []);

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', [$fechaFin]);

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', []);

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacto($contacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacto', [$contacto]);

        return parent::setContacto($contacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacto', []);

        return parent::getContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrochure($brochure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrochure', [$brochure]);

        return parent::setBrochure($brochure);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrochure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrochure', []);

        return parent::getBrochure();
    }

    /**
     * {@inheritDoc}
     */
    public function addComentario(\ComentarioBundle\Entity\Comentario $comentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComentario', [$comentario]);

        return parent::addComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComentario(\ComentarioBundle\Entity\Comentario $comentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComentario', [$comentario]);

        return parent::removeComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', [$area]);

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setRama($rama = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRama', [$rama]);

        return parent::setRama($rama);
    }

    /**
     * {@inheritDoc}
     */
    public function getRama()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRama', []);

        return parent::getRama();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisciplina($disciplina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisciplina', [$disciplina]);

        return parent::setDisciplina($disciplina);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisciplina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisciplina', []);

        return parent::getDisciplina();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

}
