<?php

namespace Proxies\__CG__\VisitasDiaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VisitasDia extends \VisitasDiaBundle\Entity\VisitasDia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'id', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'dia', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'visitas', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'visitasMes'];
        }

        return ['__isInitialized__', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'id', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'dia', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'visitas', '' . "\0" . 'VisitasDiaBundle\\Entity\\VisitasDia' . "\0" . 'visitasMes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VisitasDia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDia($dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', [$dia]);

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', []);

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisitas($visitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisitas', [$visitas]);

        return parent::setVisitas($visitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisitas', []);

        return parent::getVisitas();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisitasMes(\VisitasMesBundle\Entity\VisitasMes $visitasMes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisitasMes', [$visitasMes]);

        return parent::setVisitasMes($visitasMes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisitasMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisitasMes', []);

        return parent::getVisitasMes();
    }

}
