
addOferta:
    path:     /addOferta/
    defaults: { _controller: OfertaBundle:Default:subirOferta }

mostrarOfertas:
    path:     /mostrarOfertas/
    defaults: { _controller: OfertaBundle:Default:mostrarOfertas }

mostrarOferta:
    path:     /mostrarOferta/
    defaults: { _controller: OfertaBundle:Default:mostrarOferta }

oferta_lista:
    path:     /area_lista/
    defaults: { _controller: OfertaBundle:Default:searchArea }

oferta_search:
    path:     /search_oferta/
    defaults: { _controller: OfertaBundle:Default:searchOferta }

send_emailOferta:
    path:     /send_email/
    defaults: { _controller: OfertaBundle:Default:sendEmail }

editOferta:
    path:     /editOferta/
    defaults: { _controller: OfertaBundle:Default:editOferta }

eliminarOferta:
    path:     /deleteOferta/
    defaults: { _controller: OfertaBundle:Default:eliminarOferta }


addOferta:
    path:     /addOferta/
    defaults: { _controller: OfertaBundle:Default:subirOferta }

sumarVisitas:
    path:     /sumarVisitas/
    defaults: { _controller: OfertaBundle:Default:sumarVisitasOferta }
