<?php

namespace DemandaBundle\Repository;

/**
 * DemandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandaRepository extends \Doctrine\ORM\EntityRepository
{
}
